# Generated by Django 4.2.2 on 2023-07-13 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='taskTitle',
            new_name='title',
        ),
    ]
